name: deploy-digitalocean
###################   prueba semantic-release
on:
  push:
    branches:
      - dev
    tags:
      - v*

env:
  IMAGE_NAME: hello-world

jobs:
  #BUILD
  build:
    #needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npx semantic-release
      - run: npm run build-admin
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Log into registry
        run: echo "${{ secrets.ACTION_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Conecta SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DEV_APIS_HOST }}
          username: ${{ secrets.DIGITALOCEAN_DEV_APIS_USER }}
          key: ${{ secrets.DIGITALOCEAN_DEV_APIS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_DEV_APIS_PASSPHRASE }}
          port: 22
          script: |
            cd /srv/hello-world && sudo docker-compose pull && sudo docker-compose up -d

